OrDuDragon/Models/AuthorisationRequired.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Autentification.Controllers
{
    public class AuthorisationRequired : AuthorizeAttribute
    {
        protected override bool AuthorizeCore(HttpContextBase httpContext)
        {
            if (httpContext.Session["User"] != null)
            {
                    return true;
            }
            HttpContext.Current.Response.Redirect("/Users/PermissionInvalide");
            return base.AuthorizeCore(httpContext);
        }
    }
}

OrDuDragon/Models/Questions.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OrDuDragon.Models
{
    public class Question
    {
        public int Id { get; set; }
        public string Enoncer { get; set; }

        public string Reponce1 { get; set; }
        public string Reponce2 { get; set; }
        public string Reponce3 { get; set; }
        public string Reponce4 { get; set; }

        public bool BonneReponce { get; set; }
        public int Dificulter { get; set; }
        public Question() { }

    }

    public class Questions
    {
    }
}

OrDuDragon/Models/Users.cs
using Oracle.DataAccess.Client;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OrDuDragon.Models
{
    public class UserViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Nom d'usager")]
        [Required]
        [StringLength(50)]
        public string UserName { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "La chaîne {0} doit comporter au moins {2} caractères.", MinimumLength = 0)]
        [DataType(DataType.Password)]
        [Display(Name = "Mot de passe")]
        public string Password { get; set; }
    }

    public class User
    {
        public OracleConnection connexion = new OracleConnection();

        private string usr;
        private string passw;
        public User() { }
        public User(UserViewModel userViewModel)
        {
            usr = userViewModel.UserName;
            passw = userViewModel.Password;
        }
        public bool LogIn()
        {
            try
            {
                string dSource = "(DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 205.237.244.251)"
                    + "(PORT = 1521)))(CONNECT_DATA =(SERVICE_NAME = orcl.clg.qc.ca)))";
                string chaine = "Data Source =" + dSource + "; User Id =" + usr + ";Password =" + passw;
                connexion.ConnectionString = chaine;
                connexion.Open();
                return true;
            }
            catch (Exception se)
            {
                return false;
            }
        }

        public void LogOut()
        {
            if (connexion.State == ConnectionState.Open)
            {
                connexion.Close();
            }
        }

     
    }
}

OrDuDragon/Controllers/HomeController.cs
using Autentification.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OrDuDragon.Controllers
{
    public class HomeController : Controller
    {
        [AuthorisationRequired]
        public ActionResult Index()
        {
            return View();
        }

        [AuthorisationRequired]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        [AuthorisationRequired]
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

OrDuDragon/Controllers/QuestionsController.cs
using Autentification.Controllers;
using Oracle.DataAccess.Client;
using OrDuDragon.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

// TODO :: handle error page create a new view for that
namespace OrDuDragon.Controllers
{
    public class QuestionsController : Controller
    {

        [AuthorisationRequired]
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        [AuthorisationRequired]
        public ActionResult Create()
        {
            Question question = new Question();
            return View(question);
        }

        [HttpPost]
        [AuthorisationRequired]
        public ActionResult Create(Question question)
        {
            User user = (User)Session["User"];

            try
            {
                //   PROCEDURE INSERTQUESTION(PENONCER IN QUESTION.ENONCER%TYPE,PDIFFICULTER IN QUESTION.DIFFICULTER%TYPE);

                // Ajout de la question
                OracleCommand oraclCommandAjoutQuestion = new OracleCommand("GESTIONQUESTION", user.connexion);
                oraclCommandAjoutQuestion.CommandText = "GESTIONQUESTION.INSERTQUESTION";
                oraclCommandAjoutQuestion.CommandType = CommandType.StoredProcedure;

                OracleParameter orapamnumEnoncer = new OracleParameter("PENONCER", OracleDbType.Varchar2, 100);
                orapamnumEnoncer.Direction = ParameterDirection.Input;
                orapamnumEnoncer.Value = question.Enoncer;
                oraclCommandAjoutQuestion.Parameters.Add(orapamnumEnoncer);

                OracleParameter orapamDificulter = new OracleParameter("PDIFFICULTER", OracleDbType.Int32);
                orapamDificulter.Direction = ParameterDirection.Input;
                orapamDificulter.Value = question.Dificulter;
                oraclCommandAjoutQuestion.Parameters.Add(orapamDificulter);

                oraclCommandAjoutQuestion.ExecuteNonQuery();

                // ########################################################################################################################################

                //  PROCEDURE INESRTREPONSE(PENONCER IN REPONSE.ENONCERREPONSE%TYPE,PBONNE IN REPONSE.ESTBONNE%TYPE,PNUMQUESTION IN REPONSE.NUMQUESTION%TYPE);

                // Ajout des choix de réponce
                OracleCommand oraclCommandAjoutReponce = new OracleCommand("GESTIONQUESTION", user.connexion);
                oraclCommandAjoutReponce.CommandText = "GESTIONQUESTION.INESRTREPONSE";
                oraclCommandAjoutReponce.CommandType = CommandType.StoredProcedure;

                // Enoncer
                oraclCommandAjoutReponce.Parameters.Add(orapamnumEnoncer);




                oraclCommandAjoutReponce.ExecuteNonQuery();

                return RedirectToAction("Index");
            }
            catch (Exception ex) {
                return RedirectToAction("Index");
            }
        }

    }
}

OrDuDragon/Controllers/UsersController.cs
using Autentification.Controllers;
using Oracle.DataAccess.Client;
using OrDuDragon.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OrDuDragon.Controllers
{
    public class UsersController : Controller
    {
        public ActionResult PermissionInvalide()
        {
            return View();
        }

        public ActionResult LogIn()
        {
            return View();
        }
        [HttpPost]
        public ActionResult LogIn(UserViewModel user)
        {
            User userConnected = new User(user);
            if (userConnected.LogIn())
            {
                Session["User"] = userConnected;
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [AuthorisationRequired]
        public ActionResult LogOut()
        {
            User userConnected = (User)Session["User"];
            userConnected.LogOut();
            Session["User"] = null;
            return RedirectToAction("LogIn", "Users");
        }

        [AuthorisationRequired]
        public ActionResult GameData()
        {
            return View();
        }
    }
}

OrDuDragon/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<div class="container">
    <h2>À propos</h2>
    <div>
        <h3>L'or du dragon</h3>
        <p>
            L’or du dragon est un jeu ou le but est de ramasser des pièces d’or afin d’acheter une auberge, un manoir et un château.  Une fois ces trois constructions réalisées le joueur gagne. Il peut en construire plus d’une. De plus, le monde est peuplé de méchant, les trolls et les gobelins.  Pour se déplacer dans le monde, le joueur peut se déplacer de case en case à sa guise mais il ne peut sauter de case sur son chemin s’il tombe sur une case où il y a un méchant il est amené en prison et s’il tombe sur un case avec une construction adverse il reçoit une question.
        </p>
        <h3>Voici les notions aquises</h3>
        <ol>
            <li>Comprendre le modèle MVC 5 dans un contexte multi-usager</li>
            <li>Comprendre et appliquer l’authentification à une application Web</li>
            <li>Gérer et utiliser les bibliothèques clientes (jQuery, bootstrap, etc.)</li>
            <li>Utilisation de requête AJAX dans une page web</li>
            <li>Utilisation d’horloge pour effectuer des rafraichissements partiels et périodiques</li>
            <li>Utilisation d’une base de données SQL Express local à l’application via la dll SQLExpressUtilities (fournie avec cet énoncé)</li>
            <li>Implanter un service qui reçoit une requête paramétré et qui retourne un résultat en JSON</li>
            <li>Utilisation de la balise html 5 « canvas » pour tracer des graphiques statistiques</li>
            <li>Tenir compte des droits d’usager pour l’accès à une action d’un contrôleur</li>
        </ol>

        <p>
            <br />
            <a href="@Url.Action("Contact", "Home")" class="btn btn-primary btn-lg">Nous contacter &raquo;</a>
        </p>
    </div>
</div>

OrDuDragon/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<div class="container">
    <h2>@ViewBag.Title.</h2>
    <div class="row">
        <div class="col-md-5">
            <h3>Nathan Arseneau</h3>
            <address>
                Étudiant<br />
                Informatique de gestion<br />
                Collège Lionel-Groulx<br />

                <abbr>
                    <small>
                        100 rue Duquet<br />
                        Sainte-Thérèse, Qc.<br />
                        J7E 3G6<br />
                    </small>
                </abbr>
            </address>
        </div>
        <div class="col-md-5">
            <h3>Jean-Phillipe Trépanier</h3>
            <address>
                Étudiant<br />
                Informatique de gestion<br />
                Collège Lionel-Groulx<br />

                <abbr>
                    <small>
                        100 rue Duquet<br />
                        Sainte-Thérèse, Qc.<br />
                        J7E 3G6<br />
                    </small>
                </abbr>
            </address>
        </div>
        <div class="col-md-5">
            <h3>Julien Gagnon</h3>
            <address>
                Étudiant<br />
                Informatique de gestion<br />
                Collège Lionel-Groulx<br />

                <abbr>
                    <small>
                        100 rue Duquet<br />
                        Sainte-Thérèse, Qc.<br />
                        J7E 3G6<br />
                    </small>
                </abbr>
            </address>
        </div>
        <div class="col-md-5">
            <h3>Nicholas Thérien Roussel</h3>
            <address>
                Étudiant<br />
                Informatique de gestion<br />
                Collège Lionel-Groulx<br />

                <abbr>
                    <small>
                        100 rue Duquet<br />
                        Sainte-Thérèse, Qc.<br />
                        J7E 3G6<br />
                    </small>
                </abbr>
            </address>
        </div>
    </div>
</div>

OrDuDragon/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<style>
    .jumbotron {
        position: relative;
        background: #000 url("/Image/capture.png") center center;
        width: 100%;
        height: 100%;
        background-size: cover;
        overflow: hidden;
    }

    h1 {
        text-align: center;
        opacity: inherit;
    }

    input {
        background-color: transparent;
        border: 5px solid white;
        color: white;
        padding: 10px;
        display: block;
        margin: 0 auto;
    }

    .feature {
        height: 250px;
        background-color: red;
    }

    .left {
        background-color: red;
    }

    .middle {
        background-color: blue;
    }

    .right {
        background-color: red;
    }
</style>
<div class="jumbotron">
    <div class="container">
        <h1>L'or du dragon</h1>
        <input type="button" value="En savoir plus" onclick="location.href='@Url.Action("About", "Home")'" />
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-4 feature left">

        </div>
        <div class="col-md-4 feature middle">

        </div>
        <div class="col-md-4 feature right">

        </div>
    </div>
</div>

<br />

OrDuDragon/Views/Questions/Create.cshtml
@model OrDuDragon.Models.Question
@{
    ViewBag.Title = "Create";
}
<style>


    h1 {
        text-align: center;
        opacity: inherit;
    }

  
</style>


<div class="container">
 

    @using (Html.BeginForm("Create", "Questions", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <h2>Création d'une Question</h2>

        @Html.AntiForgeryToken()
        <div class="row">
            <div class="form-horizontal">
                <div class="row col-md-12">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.Enoncer, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Enoncer, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                            @Html.ValidationMessageFor(model => model.Enoncer, "", new { @class = "text-danger" })


                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Reponce1, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Reponce1, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                            @Html.ValidationMessageFor(model => model.Reponce1, "", new { @class = "text-danger" })
                            <input type="checkbox" name="good" value="1">
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Reponce2, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Reponce2, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                            @Html.ValidationMessageFor(model => model.Reponce2, "", new { @class = "text-danger" })
                            <input type="checkbox" name="good" value="2">
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Reponce3, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Reponce3, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                            @Html.ValidationMessageFor(model => model.Reponce3, "", new { @class = "text-danger" })
                            <input type="checkbox" name="good" value="3">

                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Reponce4, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Reponce4, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                            @Html.ValidationMessageFor(model => model.Reponce4, "", new { @class = "text-danger" })
                            <input type="checkbox" name="good" value="4">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-2">
            

           
            
        </div>

        <div class="row">
            <div class="col-md-offset-9 col-md-6">
                <input type="button" class="btn btn-cancel btn-primary" value="Annuler" onclick="location.href='@Url.Action("Index", "Questions")'" />
                <input type="submit" id="submit" value="Ajouter la question" class="btn btn-primary" />
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $("input:checkbox").on('click', function () {
            var $box = $(this);
            if ($box.is(":checked")) {
                var group = "input:checkbox[name='" + $box.attr("name") + "']";
                $(group).prop("checked", false);
                $box.prop("checked", true);
            } else {
                $box.prop("checked", false);
            }
        });
    </script>
}

OrDuDragon/Views/Questions/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="container">
    <h2>Question</h2>

    <div class="form-group">

        <input type="button" class="btn btn-cancel btn-primary" value="Ajouter une question" onclick="location.href='@Url.Action("Create", "Questions")'" />

    </div>
    
    <div class="form-group">

        <input type="button" class="btn btn-cancel btn-primary" value="Lister les questions " onclick="location.href='@Url.Action("Create", "Questions")'" />

    </div>
   


</div>

OrDuDragon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        #sidebar {
            z-index: 1;
            position: fixed;
            width: 0;
            height: 100%;
            overflow-y: hidden;
            background-color: #121519;
        }

        #content {
            color:white;
            height:100%;
            background-color:#2a333c;
            width: 100%;
            position: absolute;
        }
        body {
            background-color:#2a333c;
        }
        @@media screen and (min-width: 720px)
        {
            #wrapper.menuDisplayed #sidebar {
                width: 250px;
            }
            #wrapper.menuDisplayed #content {
                padding-left: 250px;
            }
            .logo {
                margin-left:-25px;
            }
            .big {
                display:inline;
            }
        }
        @@media screen and (max-width: 720px)
        {
            #wrapper.menuDisplayed #sidebar {
                width: 50px;
            }
            #wrapper.menuDisplayed #content {
                padding-left: 50px;
            }
            .big {
                display:none;
            }
            .logo {
                left:-25px;
            }
        }

        .sidebar-nav {
             padding: 0;
             list-style: none;
        }

        .sidebar-nav li {
            text-indent: 20px;
            line-height: 40px;
        }

        .sidebar-nav li a {
            display: block;
            text-decoration: none;
            text-align:left;
            color: #ddd;
        }

        .sidebar-nav li a:hover {
            background-color:dodgerblue;
        }
        footer p{
            text-align:center;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <button id="toggle-side-bar" type="button" class="btn btn-primary navbar-btn" aria-label="Left Align">
                    <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Se déconnecter", "LogOut", "Users")</li>
                </ul>

            </div>
        </div>
    </nav>
    <div id="wrapper">
        <div id="sidebar">
            <ul class="sidebar-nav">
                <li>
                    <a href="@Url.Action("Index", "Home")">
                        <span class="logo glyphicon glyphicon-home" aria-hidden="true"></span>
                        <p class="big">Accuil</p>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("GameData", "Users")">
                        <span class="logo glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                        <span class="big">Ressources</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Questions")">
                        <span class="logo glyphicon glyphicon-question-sign" aria-hidden="true"></span>
                        <span class="big">Question</span>
                    </a>
                </li>
            </ul>
        </div>
        <div id="content">
            <div class="container-fluid">
                @RenderBody()
            </div>
            <footer class="container">
                <p>&copy; @DateTime.Now.Year - L'or du dragon</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        $("#toggle-side-bar").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("menuDisplayed");
        });
    </script>
</body>
</html>

OrDuDragon/Views/Users/GameData.cshtml
@{
    ViewBag.Title = "GameData";
}
<style>
    .item-image {
        width: 120px;
        height: 120px;
    }

    .item {
        margin-right: 20px;
        margin-bottom: 20px;
        padding: 10px;
        display: flex;
        width: 300px;
        height: 120px;
        background-color: #474C54;
    }

    .item-amount {
        font-size:40px;
        position: relative;
        padding-top:25px;
        margin-left:50px;
        vertical-align: central;
        color: white;
        text-align: right;
    }
</style>
<div class="container">
    <h2>Ressources</h2>

    <div class="row">
        <div class="item col-md-4">
            <img class="item-image" src="~/Image/gold.png" />
            <p class="item-amount">50 G</p>
        </div>
        <div class="item col-md-4">
            <img class="item-image" src="~/Image/mountainDew.png" />
            <p class="item-amount">5</p>
        </div>
        <div class="item col-md-4">
            <img class="item-image" src="~/Image/doritos.png" />
            <p class="item-amount">5</p>
        </div>
        <div class="item col-md-4">
            <img class="item-image" src="~/Image/auberge.png" />
            <p class="item-amount">5</p>
        </div>
        <div class="item col-md-4">
            <img class="item-image" src="~/Image/manor.png" />
            <p class="item-amount">5</p>
        </div>
        <div class="item col-md-4">
            <img class="item-image" src="~/Image/castle.png" />
            <p class="item-amount">5</p>
        </div>
    </div>
</div>

OrDuDragon/Views/Users/LogIn.cshtml
@model OrDuDragon.Models.UserViewModel

@{
    ViewBag.Title = "Connexion";
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .center {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%,-50%);
        }

        #background {
            background-color: #121519;
            border: none;
        }

        #content {
            background-color: white;
            padding: 25px;
        }

        input {
            width: 100%;
        }

        #title {
            background-color: dodgerblue;
        }

        #new-account {
            text-align: center;
        }
        h2 {
            color:white;
            text-align:center;
            margin:0px;
            padding:25px;
        }
    </style>
</head>
<body id="background">
    <div class="container center" ­>
        <div class="col-md-12">
            <div id="title">
                <h2>Connexion</h2>
            </div>
            <div id="content">
                @using (Html.BeginForm())
            {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true)

                        <div class="form-group">
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Username", autocomplete = "off" } })
                                @Html.ValidationMessageFor(model => model.UserName)
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @placeholder = "Password", autocomplete = "off" } })
                                @Html.ValidationMessageFor(model => model.Password)
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Connexion" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

OrDuDragon/Views/Users/PermissionInvalide.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        body {
            background-color:#2a333c;
            color:white;
        }


    </style>
</head>
<body>
    <div class="container">

        <h2>Acces refusé</h2>
        <p>
            Malheureusement vous n'avez pas la permission de venir sur cette page, vous n'êtes
            connecté.  Si vous désirer devenir un utilisateur vous avez toujours la
            possibilliter de vous inscrir.
        </p>

        <button class="btn btn-primary" onclick="location.href='@Url.Action("LogIn", "Users")'">Nous contacter  &raquo;</button>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>